### ISSUE TITLE
BigQuery tables failing on local mode when PROJECT: is not specified as part of the table

### ISSUE THREAD

**Issue by javier** [GoogleCloudPlatform/DataflowPythonSDK#1]
When trying to execute locally a pipeline using bigquery, if the DATASET.TABLE form is passed a missing project error is raised, even when --project is passed explicitly.

I was going to try and fix it but when I checked the source at
https://github.com/GoogleCloudPlatform/DataflowPythonSDK/blob/master/google/cloud/dataflow/io/bigquery.py  I found out a TODO comment to try and get that automatically from the environment, so I decided not to work on it as it seemed more work was planned on this.

To test this issue, just try and run locally the bigquery_tornadoes cookbook example specifying a project id as a command line argument, but using DATASET.TABLE for the table, without the fully qualified name.

Thanks

**Comment by silviulica** [comment]
Thanks Javier. This is already in the pipeline of things to be fixed in the next (soon) release.

**Comment by javier** [comment]
Awesome. Thanks
