### ISSUE TITLE
Datastore source and sink

### ISSUE THREAD

**Issue by gpopovic** [GoogleCloudPlatform/DataflowPythonSDK#10]
Is there any ETA for Datastore as a source and sink?

**Comment by silviulica** [comment]
We cannot share an ETA but it is on our radar as something multiple customers asked for.

**Comment by gpopovic** [comment]
Any news on this? It will be especially useful when new datastore pricing starts and indexes will be "free".

**Comment by aaltay** [comment]
Datastore support is available in the current version:

https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/datastore/v1/datastoreio.py
