### ISSUE TITLE
wordcount.py example  " Import by filename is not supported"

### ISSUE THREAD

**Issue by ThomRogers** [GoogleCloudPlatform/DataflowPythonSDK#11]
Using Ubuntu 14.04, 
DataFlow Python SDK
 
Following instructions at [https://github.com/GoogleCloudPlatform/DataflowPythonSDK#status-of-this- release]  , after everything is loaded when I trythe wordcount example I try get the error "Import by filename is not supported".

I suspect the issue is at line 23

    import google.cloud.dataflow as df

Is there a workaround for this issue?

Thanks,
Thom

**Comment by silviulica** [comment]
Can you please share your the console output?

**Comment by ThomRogers** [comment]
`(dataflow-beam) bd-01@bd01-Aspire-E1-531:~/dataflow-beam/bin$ python -m google.cloud.dataflow.examples.wordcount --output word_out.txt

/usr/bin/python3: Error while finding spec for 'google.cloud.dataflow.examples.wordcount' (<class 'ImportError'>: No module named 'google')

(dataflow-beam) bd-01@bd01-Aspire-E1-531:~/dataflow-beam/bin$ ~/dataflow-beam/bin/python -m /lib/python2.7/site-packages/google/cloud/dataflow/examples/wordcount   --output count_words.txt

/home/bd-01/dataflow-beam/bin/python: Import by filename is not supported.
`

**Comment by silviulica** [comment]
Hi,
Let's try to take un-tagle what is going on. How about (if you have time) try this:
1) create/activate a virtual env (conda or virtual env or whatever you use). You need an environment with py2.7 -- we do not support py3.0 yet.
2) cd to some empty work directory (~/xyz for instance) 
3) Run: pip install https://github.com/GoogleCloudPlatform/DataflowPythonSDK/archive/v0.2.3.tar.gz
4) At this point if you start python you should be able to run w/o errors the following:
import google.cloud.dataflow as df
5) copy/paste the wordcount example in a file and run it. Should work.
I never tried to run straight from the installation point and we do not really intend to support that.

**Comment by ThomRogers** [comment]
Followed your suggestion above and am now getting error "ImportError: No module named google.cloud.dataflow"

Inserting screenshot of session, here are some comments, by line:

I invoke Python2.7 by absolute path because if I just type in "python", it brings up python3.4.3 which is also installed on my machine.
    
    (try_fix) bd-01@bd01-Aspire-E1-531:~$ /home/bd01/try_fix/bin/python2.7

I made the empty working directory in the virtual env.
    
    (try_fix) bd-01@bd01-Aspire-E1-531:~$ sudo mkdir /home/bd01/try_fix/testing

I also tried it with the empty working directory outside the virtual env
    
    (try_fix) bd-01@bd01-Aspire-E1-531:/home/bd01/try_fix/testing$ cd ~/today

Here's the whole session:
![import_df04211601](https://cloud.githubusercontent.com/assets/10057394/14721683/ff027372-07c4-11e6-9ffa-94f402c0923f.png)

**Comment by silviulica** [comment]
There must be something unusual with the python 2.7 vs python 3.4 environments that escapes me. If you do pip install dataflow-sdk-.....tarbal and then you launch python -v what do you see?
-v will show all the places where it looks to load modules. After that if you do import google.cloud.dataflow you should see where it looks for the module.

Also run a pip freeze to check that dataflow is installed in the virtual environment you are running this from.

**Comment by ThomRogers** [comment]
Thanks for your patience and diligence in trying to get this sorted.

pip freeze doesn't show anything, it just advances a line on the console and shows an empty prompt I did this after the python -v, just showing the results in this post first.:

    (try_fix) bd-01@bd01-Aspire-E1-531:~/today$ pip freeze
    (try_fix) bd-01@bd01-Aspire-E1-531:~/today$ 


/home/bd01/try_fix/bin/python2.7 -v gives me a long list of stuff:  

`(try_fix) bd-01@bd01-Aspire-E1-531:~/today$ /home/bd01/try_fix/bin/python2.7 -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /home/bd01/try_fix/lib/python2.7/site.pyc matches /home/bd01/try_fix/lib/python2.7/site.py
import site # precompiled from /home/bd01/try_fix/lib/python2.7/site.pyc
# /home/bd01/try_fix/lib/python2.7/os.pyc matches /home/bd01/try_fix/lib/python2.7/os.py
import os # precompiled from /home/bd01/try_fix/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /home/bd01/try_fix/lib/python2.7/posixpath.pyc matches /home/bd01/try_fix/lib/python2.7/posixpath.py
import posixpath # precompiled from /home/bd01/try_fix/lib/python2.7/posixpath.pyc
# /home/bd01/try_fix/lib/python2.7/stat.pyc matches /home/bd01/try_fix/lib/python2.7/stat.py
import stat # precompiled from /home/bd01/try_fix/lib/python2.7/stat.pyc
# /home/bd01/try_fix/lib/python2.7/genericpath.pyc matches /home/bd01/try_fix/lib/python2.7/genericpath.py
import genericpath # precompiled from /home/bd01/try_fix/lib/python2.7/genericpath.pyc
# /home/bd01/try_fix/lib/python2.7/warnings.pyc matches /home/bd01/try_fix/lib/python2.7/warnings.py
import warnings # precompiled from /home/bd01/try_fix/lib/python2.7/warnings.pyc
# /home/bd01/try_fix/lib/python2.7/linecache.pyc matches /home/bd01/try_fix/lib/python2.7/linecache.py
import linecache # precompiled from /home/bd01/try_fix/lib/python2.7/linecache.pyc
# /home/bd01/try_fix/lib/python2.7/types.pyc matches /home/bd01/try_fix/lib/python2.7/types.py
import types # precompiled from /home/bd01/try_fix/lib/python2.7/types.pyc
# /home/bd01/try_fix/lib/python2.7/UserDict.pyc matches /home/bd01/try_fix/lib/python2.7/UserDict.py
import UserDict # precompiled from /home/bd01/try_fix/lib/python2.7/UserDict.pyc
# /home/bd01/try_fix/lib/python2.7/_abcoll.pyc matches /home/bd01/try_fix/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /home/bd01/try_fix/lib/python2.7/_abcoll.pyc
# /home/bd01/try_fix/lib/python2.7/abc.pyc matches /home/bd01/try_fix/lib/python2.7/abc.py
import abc # precompiled from /home/bd01/try_fix/lib/python2.7/abc.pyc
# /home/bd01/try_fix/lib/python2.7/_weakrefset.pyc matches /home/bd01/try_fix/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /home/bd01/try_fix/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /home/bd01/try_fix/lib/python2.7/copy_reg.pyc matches /home/bd01/try_fix/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /home/bd01/try_fix/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /home/bd01/try_fix/lib/python2.7/encodings
# /home/bd01/try_fix/lib/python2.7/encodings/__init__.pyc matches /home/bd01/try_fix/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /home/bd01/try_fix/lib/python2.7/encodings/__init__.pyc
# /home/bd01/try_fix/lib/python2.7/codecs.pyc matches /home/bd01/try_fix/lib/python2.7/codecs.py
import codecs # precompiled from /home/bd01/try_fix/lib/python2.7/codecs.pyc
import _codecs # builtin
# /home/bd01/try_fix/lib/python2.7/encodings/aliases.pyc matches /home/bd01/try_fix/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /home/bd01/try_fix/lib/python2.7/encodings/aliases.pyc
# /home/bd01/try_fix/lib/python2.7/encodings/utf_8.pyc matches /home/bd01/try_fix/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /home/bd01/try_fix/lib/python2.7/encodings/utf_8.pyc
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/home/bd01/try_fix/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /home/bd01/try_fix/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
>>> import google.cloud.dataflow 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named google.cloud.dataflow
>>> import google.cloud.dataflow as df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named google.cloud.dataflow
>>> quit()
`

**Comment by ThomRogers** [comment]
Finally got it working!!  Thanks to @silviulica  who broke down the barrier with his advice at https://stackoverflow.com/questions/36816528/dataflow-wordcount-py-example-import-by-filename-is-not-supported

Turns out I was using sudo to invoke my virtual env and my "pip install ..SDK" from the shell, so when I was local, I had no access to the SDK.

This seems basic now, but here are the steps that I documented that give me a working usable virtual env as local user:

    ###Get current installed versions  
    # This part is optional, but useful if you have to ask for help
    #  uname -r  			returns  kernel release number
    #  lsb_release -a   	returns  linux version
    #  virtualenv --version  returns package version (virtualenv in this case)
    #  echo "kernel is ...  ";uname -r; echo "" ; lsb_release -a;  echo "" ; echo "virtualenv version is ...  "; virtualenv --version
   

    $ mkdir <new_dir_for_virtualenv>
    $ virtualenv  <new_dir_for_virtualenv>     
    $ source <new_dir_for_virtualenv>/bin/activate  # activates the virtual env
    $ pip install https://github.com/GoogleCloudPlatform/DataflowPythonSDK/archive/v0.2.3.tar.gz  # loads the SDK
    $ python2.7  
    >>> import google.cloud.dataflow as df
    >>> quit()
    $ pip freeze  # list of installed pkgs should include "python-dataflow==0.2.3"
