### ISSUE TITLE
Is compression_type supported for TextFileSource

### ISSUE THREAD

**Issue by brightsparc** [GoogleCloudPlatform/DataflowPythonSDK#12]
Hi,

I'm passing in a .gzip file and have tried compression_type='AUTO' as well as 'GZIP' and am getting when when reading a line 

```
  File "/usr/local/lib/python2.7/site-packages/google/cloud/dataflow/io/fileio.py", line 313, in __iter__
    yield self.source.coder.decode(line)
  File "<stdin>", line 7, in decode
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

It seems that the file open command needs to be extended to support gzip.open
https://github.com/GoogleCloudPlatform/DataflowPythonSDK/blob/master/google/cloud/dataflow/io/fileio.py#L268

```
import gzip
f = gzip.open(self.source.file_path, 'rb')
f.readline()
```

Cheers,
Julian.

**Comment by silviulica** [comment]
Just to confirm. We do not support compressed files yet.

**Comment by igrigorik** [comment]
Do we know when this will be available? Ish?

**Comment by silviulica** [comment]
The way to deal with this is to use the custom source framework. This is already in the current release however we are also working on a simplified framework for file-based sources. With this in, everybody will be able to add support for compressed files. See https://github.com/GoogleCloudPlatform/DataflowPythonSDK/blob/master/google/cloud/dataflow/io/iobase.py#L322

**Comment by abhishekjha13091989** [comment]
Is it the official code given by google for dataflow?

**Comment by silviulica** [comment]
Dataflow code is written by Google (initially) and open-sourced. Please note that the Dataflow model and SDK is now an Apache incubating project (Apache Beam): http://beam.incubator.apache.org/
We just moved the Python SDK code in the Apache Beam repo and we are rewiring all our code/tooling to do development and releases based on this code: https://github.com/apache/incubator-beam/tree/python-sdk/sdks/python

**Comment by aaltay** [comment]
@igrigorik compression is now supported in Beam (https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/fileio.py)

@abhisheksears Code is available at https://github.com/apache/beam/tree/master/sdks/python

**Comment by igrigorik** [comment]
\o/ ... thanks!
