### ISSUE TITLE
Invoking correct Python version when higher versions are already installed

### ISSUE THREAD

**Issue by ThomRogers** [GoogleCloudPlatform/DataflowPythonSDK#15]
The install directons at  https://github.com/GoogleCloudPlatform/DataflowPythonSDK#status-of-this-  instruct the user to invoke python by `python -m google.cloud.dataflow.examples.wordcount --output OUTPUT_FILE`  

But if the user already has Python 3.4.3 (or probably **any** other python version) installed, then typing `python` will open the 3.4.3 (or other previously installed?) version.  The user needs to invoke all python calls with `python2.7` in order to run the correct version of Python to run the Dataflow SDK.

This is true even though the $PATH env var in the virtual env begins with `/home/<name_of_virtual_env>/bin:`

So in order to get the example to work, user needs to use `python2.7 -m google.cloud.dataflow.examples.wordcount --output OUTPUT_FILE`

**Comment by silviulica** [comment]
Acknowledged. Will add an error message with the next release.
