### ISSUE TITLE
Dataflow 0.2.7 custom commands not working

### ISSUE THREAD

**Issue by gpopovic** [GoogleCloudPlatform/DataflowPythonSDK#20]
Custom commands written in setup.py stopped working in dataflow 0.2.7.

I removed dataflow 0.2.7, installed dataflow 0.2.6 and it works.

**Comment by silviulica** [comment]
Thanks! We switched from installing using easy_install to using pip install for the SDK package. 
This does not use eggs anymore so the bdist_egg function will not be invoked anymore: https://github.com/GoogleCloudPlatform/DataflowPythonSDK/blob/master/google/cloud/dataflow/examples/complete/juliaset/setup.py#L31

We will post a workaround. Do not remember of the top of my head but there is an equivalent approach for pip install scenarios.

**Comment by charlesccychen** [comment]
Thanks.  Please refer to https://github.com/apache/incubator-beam/pull/491 for an example of how to use custom commands with 0.2.7.
