### ISSUE TITLE
links in README point to localhost

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/DataflowPythonSDK#21]
The [links](/GoogleCloudPlatform/DataflowPythonSDK#a-quick-tour-of-the-source-code) in the top-level README point to localhost:8080

**Comment by aaltay** [comment]
The links were about hosting pydocs locally. Now pydocs are hosted on Apache Beam website, there is no need to do that: https://beam.apache.org/documentation/sdks/pydoc/0.6.0/
