### ISSUE TITLE
Cannot use service account credentials

### ISSUE THREAD

**Issue by nickmoorman** [GoogleCloudPlatform/DataflowPythonSDK#23]
Trying to use a service account to run a Dataflow pipeline by passing `--service_account_name` and `--service_account_key_file` fails with:

```
TypeError: from_p12_keyfile() got an unexpected keyword argument 'user_agent'
```

Tracing through the code, I found that [that method](https://github.com/google/oauth2client/blob/v2.2.0/oauth2client/service_account.py#L310) doesn't support the `user_agent` argument.  Simply updating the signature seems to fix the problem.

**Comment by aaltay** [comment]
This is now fixed. (https://github.com/apache/beam/blob/9d3b0db2d99b6040751410f7b4196c02c72077c9/sdks/python/apache_beam/internal/gcp/auth.py#L152) Thank you for reporting.
