### ISSUE TITLE
BigQuery `DATE` support

### ISSUE THREAD

**Issue by pbeshai** [GoogleCloudPlatform/DataflowPythonSDK#25]
It would be great if the BigQuery API supported the DATE type, not currently handled in the `convert_row_to_dict` function here:
https://github.com/GoogleCloudPlatform/DataflowPythonSDK/blob/master/google/cloud/dataflow/io/bigquery.py#L819

**Comment by aaltay** [comment]
`DATE` types are supported in the latest version:

https://github.com/apache/beam/blob/1512714d2c5fdc05f2012ed7584a060217d9ee65/sdks/python/apache_beam/io/gcp/bigquery.py#L1043
