### ISSUE TITLE
Dataflow version

### ISSUE THREAD

**Issue by gpopovic** [GoogleCloudPlatform/DataflowPythonSDK#26]
Since dataflow python development moved to apache beam git, nothing has been published in this repository.

Does this mean that we should still use old version (https://github.com/GoogleCloudPlatform/DataflowPythonSDK/releases/latest )?

Its all very confusing....

**Comment by dovy** [comment]
+1

**Comment by charlesccychen** [comment]
Yes, running workflows with the release there will still work and are supported, provided you have been whitelisted.

Future releases of the Dataflow SDK will be based off of Apache Beam, as you point out, so at that time, pipelines writers will need to do some fairly straightforward refactoring.

**Comment by dovy** [comment]
So it's best to start from the beam side.

**Comment by charlesccychen** [comment]
We don't yet have a stable release of Beam out.  In the meantime, the SDK release here is the best option.  Essentially, the refactoring will mostly be renaming the Dataflow imports to become Beam imports.

**Comment by gpopovic** [comment]
@charlesccychen any ETA when we'll be able to switch to beam? I know googlers rarely say exact dates, but :D any estimate would be useful

**Comment by dovy** [comment]
Awesome. I'll start here then.  :)   Care to look at my other question?  :)

**Comment by charlesccychen** [comment]
@gpopovic I can't give a timeframe, but we're working very hard to get this out to our users soon.

**Comment by dovy** [comment]
Any progress on an ETA? Really want to move to Dataflow, but I need streaming.  :-/

**Comment by charlesccychen** [comment]
Sorry, we don't yet have an ETA.

**Comment by dovy** [comment]
Are we talking weeks, months? Haha. I've been waiting for the python streaming for nearly a year now.

**Comment by aaltay** [comment]
Closing this. Streaming for DirectRunner is in the works (https://issues.apache.org/jira/browse/BEAM-1265) and streaming in general will follow that.
