### ISSUE TITLE
Pubsub Source

### ISSUE THREAD

**Issue by dovy** [GoogleCloudPlatform/DataflowPythonSDK#27]
Can I use pubsub yet? I know we don't have "streaming", but I thought that was waiting after a pubsub topic was empty.

I need to use pubsub as my source, or put a router in front, or I can't even use Dataflow yet.  :(

Not going to use Java over here...

**Comment by charlesccychen** [comment]
This is currently not supported as an SDK primitive.  You can, however, shell out to the gcloud PubSub CLI and send messages that way.  When you run commands this way, API calls will execute as your GCP project's Compute Engine service account.  This way, you can publish messages through this CLI tool.  This workaround should work, but it isn't officially supported.

**Comment by dovy** [comment]
Care to provide any examples?  I'd love to implement this asap.  :)

**Comment by charlesccychen** [comment]
See, for example: https://cloud.google.com/sdk/gcloud/reference/alpha/pubsub/ and https://cloud.google.com/sdk/gcloud/reference/alpha/pubsub/topics/publish

**Comment by dovy** [comment]
My bad, I meant the reverse way. I want to process pubsub as a source...  Have to get my terminology down.

**Comment by charlesccychen** [comment]
Ah.  No, sorry, this functionality isn't available yet, and is on our streaming roadmap.

**Comment by dovy** [comment]
Any form of an ETA? heh.

**Comment by charlesccychen** [comment]
Sorry, I can't provide one here.

**Comment by dovy** [comment]
Email? Slack?  ;). Dovy@owletcare.com
