### ISSUE TITLE
Whitelisting required message references docs that don't mention whitelisting

### ISSUE THREAD

**Issue by cb01** [GoogleCloudPlatform/DataflowPythonSDK#3]
On submission of python dataflow job get the following message which references https://cloud.google.com/dataflow/ for more info on whitelisting but no mention of it there (https://cloud.google.com/s/results?q=whitelisting&p=%2Fdataflow%2F).

***************************************************************
*      WARNING: PROJECT WHITELISTING REQUIRED.                *
***************************************************************
Please make sure your project is whitelisted for running
Python-based pipelines using the Google Cloud Dataflow service.

You may ignore this message if you have successfully ran
Python-based pipelines with this project on Google Cloud
Dataflow service before.

If your project is not whitelisted, your job will attempt to run
however it will fail to make any progress. Google Cloud Dataflow
service will automatically cancel your non-whitelisted job
after some time due to inactivity. You can also manually cancel
your job using the following command:

gcloud alpha dataflow jobs --project=NNNN cancel 2016-03-10_11_33_46-NNNN

Please refer to the documentation to learn more about whitelisting
your project at: https://cloud.google.com/dataflow/
***************************************************************

**Comment by silviulica** [comment]
Ack. We will fix it. If you are interested in whitelisting please send a mail to dataflow-feedback@google.com and we will walk you through the steps.

**Comment by cb01** [comment]
Thank you!! Very happy about there being a Python SDK, great work!

**Comment by aaltay** [comment]
This is fixed by [Change whitelist warning URL to the signup form ](https://github.com/GoogleCloudPlatform/DataflowPythonSDK/commit/43e4942d12159c210d2238d84be6df17a7888148)

URL points to the whielisting signup form.
