### ISSUE TITLE
oauth2client.contrib.multistore_file on import

### ISSUE THREAD

**Issue by plumSemPy** [GoogleCloudPlatform/DataflowPythonSDK#34]
Hello, please see below.

$ python -v 
> `import apache_beam`
...
```python
import oauth2client.contrib.multistore_file # precompiled from /Users/emin/anaconda/lib/python2.7/site-packages/oauth2client/contrib/multistore_file.pyc
No handlers could be found for logger "oauth2client.contrib.multistore_file"
```
...

**Comment by aaltay** [comment]
Thank you @plumSemPy for reporting this. This warning should be harmless. I created bug in the beam jira, it is the master tracking list now:

https://issues.apache.org/jira/browse/BEAM-1183

Please feel free to contribute or add more details there.

**Comment by aaltay** [comment]
Closing this in favor of the tracking issue in BEAM (https://issues.apache.org/jira/browse/BEAM-1183). Thank you for reporting.
