### ISSUE TITLE
Read from BigQuery breaks on EU datasets

### ISSUE THREAD

**Issue by carlozamagni** [GoogleCloudPlatform/DataflowPythonSDK#44]
Hello i'm experiencing a problem similar to this one reported for the Java SDK: [https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/405](url)

Running on "DirectRunner" (sdk 2.0.0) the BigQuery reader breaks on EU datasets with the error:
`{ "domain": "global", "reason": "invalid", "message": "Cannot read and write in different locations: source: EU, destination: US" }`.

This is how i'm using it, just in case... `| 'Read from BQ table' >> beam.io.Read(beam.io.BigQuerySource(query=READ_QUERY))`

**Comment by chamikaramj** [comment]
This is currently not supported for queries.

https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/bigquery.py#L635
https://issues.apache.org/jira/browse/BEAM-1909

**Comment by chamikaramj** [comment]
I believe DataflowRunner should work without issues. The JIRA above is for DirectRunner.

**Comment by garcianavalon** [comment]
Any update on this issue?

**Comment by moander** [comment]
I experience the same issue. And since EU Datastore won't export to US storage location I have to first export, then copy, then bigquery.

**Comment by SampoDev** [comment]
Any update on this fatal issue? 
 "message" : "Cannot read and write in different locations: source: US, destination: EU",

**Comment by michan85** [comment]
This code is a workaround, it allows you to specify the default_loaction for the query, its not great but an interim solution

https://gist.github.com/michan85/28dba73fbe0f1121d383bf1d4aa69c73

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
