### ISSUE TITLE
Using Cloud SQL as source or sink

### ISSUE THREAD

**Issue by 1byxero** [GoogleCloudPlatform/DataflowPythonSDK#49]
I was interested in using cloud sql for source and sinks. After some reading online i realised its not available in python sdk, but is available in java sdk. 

Is there a way to do this or any future plans for the same?

If need be I can try for a PR if you guys can guide me through it

@aaltay

**Comment by 1byxero** [comment]
@aaltay

**Comment by Somtom** [comment]
I would also be interested in using Cloud SQL with the PythonSDK.
I currently have a workaround which uses CloudSQL Proxy on my PC. I connect with `psycopg2` and a custom ParDo operation. Nevertheless, the Proxy won't run on Dataflow

**Comment by 1byxero** [comment]
Tried something similar with CloudSQL Proxy, It didn't work for dataflow runner

**Comment by lukecwik** [comment]
Being tracked in https://issues.apache.org/jira/browse/BEAM-2097

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
