### ISSUE TITLE
List of Known issues

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/DataflowPythonSDK#5]
I am interested in knowing the compatibility gaps and known issues compared to the DataflowJavaSDK. Is there a list or a compilation? Given the age of the project I am guessing that it is not feature complete.

**Comment by aeneaswiener** [comment]
Yes this was not clear to me form the readme, would appreciate more detail on this.

**Comment by aeneaswiener** [comment]
Thanks for the update! Looking forward to the progress and testing once some of the above features are included (mainly streaming and custom sources allowing for things like Cloud Pub/Sub.)

**Comment by aaltay** [comment]
Update on the list above:
* Custom sources and sinks are supported.
* Product is generally available.

We moved the project to the larger Beam project, and issue tracker for all known issues/remaining task could be found on Beam JIRA [sdk-py](https://issues.apache.org/jira/browse/BEAM-804?jql=project%20%3D%20BEAM%20AND%20component%20%3D%20sdk-py%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20due%20ASC%2C%20priority%20DESC%2C%20created%20ASC) component.
