### ISSUE TITLE
Streaming jobs to gcs output

### ISSUE THREAD

**Issue by lboudard** [GoogleCloudPlatform/DataflowPythonSDK#50]
Hi,

I wanted to check the status of the issue mentioned here
https://stackoverflow.com/questions/47049337/python-apache-beam-dataflow-runner

that mentions that gcs connector is not usable yet in streaming context with python sdk (available in Java https://stackoverflow.com/questions/46909579/write-streaming-data-to-gcs-using-apache-beam)

Can you update us on this?

Thanks!

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
