### ISSUE TITLE
worker_machine_type flag is not working

### ISSUE THREAD

**Issue by dumkar** [GoogleCloudPlatform/DataflowPythonSDK#52]
When using the `worker_machine_type` flag, the VM machine type is always the standard one. 
Replacing this by `machine_type` solved my issue (see [Stackoverflow](https://stackoverflow.com/questions/49790580/worker-machine-type-tag-not-working-in-google-cloud-dataflow-with-python/49811037#49811037) for details).

This is a mistake in the [documentation](https://cloud.google.com/dataflow/pipelines/specifying-exec-params) I suppose?

**Comment by jmwoloso** [comment]
`streaming` doesn't seem to work either (at least with `DirectRunner`)

#56

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
