### ISSUE TITLE
Unable to work with google-cloud-bigquery with dataflow

### ISSUE THREAD

**Issue by OrielResearchCure** [GoogleCloudPlatform/DataflowPythonSDK#53]
Hi all,

I would like to get the latest version of bigquery working on dataflow workers (or at least newer than 0.25.0)
What will be the easier way to make this work.
Having setup.py with google-cloud-bigquery==0.28.0 will fail the installtion of the workflow right at the workers-startup time.

As you can see from this link: https://cloud.google.com/bigquery/docs/python-client-migration
the google-cloud-bigquery 0.25.0 that is latest version that is currently supported on dataflow (i think) is very cumbersome and inefficient.
Please let me know if you have any advice.

Many thanks,
eilalan

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
