### ISSUE TITLE
unable to import beam

### ISSUE THREAD

**Issue by bbarnes52-zz** [GoogleCloudPlatform/DataflowPythonSDK#54]
Seems to be an instance of: https://github.com/GoogleCloudPlatform/DataflowPythonSDK/issues/2

Error:
```
>>> import apache_beam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/virtualenv/local/lib/python2.7/site-packages/apache_beam/__init__.py", line 88, in <module>
    from apache_beam import coders
ImportError: cannot import name coders
```

I'm running Ubuntu 16.04.

Steps to reproduce:

```
$ virtualenv venv
$ source venv/bin/activate
(venv) $ pip install apache-beam
```

then try importing beam in Python shell

**Comment by bbarnes52-zz** [comment]
This error does not occur if I do `pip install apache-beam==2.4.0`

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
