### ISSUE TITLE
Install oracle instantclient in google cloud dataflow worker in python project 

### ISSUE THREAD

**Issue by finarb** [GoogleCloudPlatform/DataflowPythonSDK#57]
This is apache beam python project deployed in dataflow. it works with directrunner but not in dataflowrunner as it cant find the oracle library. everything works apart from the last line which gives an error directory now found (not sure which is the directory it means)...To confirm I had used the tree command earlier and the directory exists /opt/oracle/instantclient_18_3

using the setup.py file i give custom commands in the format(https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/complete/juliaset/setup.py)

  ```
  CUSTOM_COMMANDS = [
        ['sudo','apt-get', 'update'],
        ['sudo','mkdir','-p','/opt/oracle'],
        ['sudo','apt-get','--assume-yes','install','unzip'],
        ['wget','https://storage.googleapis.com/facbeambucketv1/files/instantclient-basic-linux.x64-18.3.0.0.0dbru.zip'],
        ['sudo','unzip','-o', 'instantclient-basic-linux.x64-18.3.0.0.0dbru.zip', '-d' ,'/opt/oracle'],
        ['sudo','unzip','-o', 'instantclient-basic-linux.x64-18.3.0.0.0dbru.zip'],
        ['sudo','apt-get','--assume-yes','install','libaio1'],
        ['sudo', 'touch', '/etc/environment'],
        ['export', 'LD_LIBRARY_PATH=/opt/oracle/instantclient_18_3']
    ]

```

I need to set the library path variable for the python package cx_oracle to work

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
