### ISSUE TITLE
403 User not authorized to perform this action.

### ISSUE THREAD

**Issue by thomas-vl** [GoogleCloudPlatform/DataflowPythonSDK#59]
Im facing the same problem as this one:
https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/220

If i try to run a pipeline with DirectRunner and i don't own the project that contains the topic dataflow tries to create the subscription in the same project as the topic instead of the project referenced in the dataflow options.

Regards,

Thomas

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
