### ISSUE TITLE
Please consider supporting Python 3

### ISSUE THREAD

**Issue by ogrisel** [GoogleCloudPlatform/DataflowPythonSDK#6]
This is a kind feature request to the developers to please consider supporting Python 3. It's quite easy to write code that works both under Python 2.7 and 3.4+ possibly with the help of tools and guidelines provided by:

http://python-future.org/

or alternatively via the older:

https://pythonhosted.org/six/

**Comment by datnamer** [comment]
+1

**Comment by silviulica** [comment]
Acknowledged! We will look into it.

**Comment by joshburkart** [comment]
Is there an ETA for this, by any chance? Might be useful to consult with the TensorFlow engineers, who have both Python 2 and 3 versions maintained simultaneously. Thanks so much!

**Comment by benjaminsims** [comment]
+1 on this - any news please? Thanks for any info!

**Comment by aaltay** [comment]
Beam tracking issue for this is: https://issues.apache.org/jira/browse/BEAM-1251. There was some additional discussion there.

**Comment by carlthome** [comment]
ETA?

**Comment by aaltay** [comment]
We do not have an ETA, and one main blocker currently is that not all of Beam Python SDK dependencies are Python 3 compatible.

**Comment by dirkjonker** [comment]
@aaltay can you elaborate on what dependencies are not Python 3 compatible? I see that _avro_ is used, which will likely never be Python 3 compatible, since there is the _avro-python3_ library for python 3 usage.

**Comment by aaltay** [comment]
I have not looked at deeply, but according to https://caniusepython3.com/project/google-cloud-dataflow there are 3. In addition to `avro` there is `google-apitools` and `httplib2`.

**Comment by dirkjonker** [comment]
@aaltay thanks for figuring that out. Does not seem to be trivial to support Python 3 if those dependencies are blocking.

**Comment by aaltay** [comment]
I am closing the issue here. For further comments please use the BEAM issue at https://issues.apache.org/jira/browse/BEAM-1251.

**Comment by sscast** [comment]
Funny that this is from 2016 and now is 2019, and Apache Beam is still not supporting python 3..

**Comment by aaltay** [comment]
Beam 2.11 added python 3 support, please take a look (https://beam.apache.org/blog/2019/03/05/beam-2.11.0.html)
