### ISSUE TITLE
Python SDK Template Creation example

### ISSUE THREAD

**Issue by swartchris8** [GoogleCloudPlatform/DataflowPythonSDK#60]
Would be great if the documentation https://cloud.google.com/dataflow/docs/guides/templates/creating-templates would have a full end to end wordcount example using templates with Python that goes from template creation to execution.

The current documentation omits details which has led for me to be unable to build a simple wordcount custom template Python job even though this should be really simple.

**Comment by aaltay** [comment]
This is available with code examples in that same page (under python tab of code examples). Do you need something else?

**Comment by swartchris8** [comment]
It doesn't work for me I think a full example repo would be what I am looking for rather than a series of snippets. If I could get custom templates working based on the snippets I wouldn't have opened this issue.

**Comment by aaltay** [comment]
cc: @azurezyq sharing this feedback that it would be good to have end to end python template examples.

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
