### ISSUE TITLE
Dataflow Python + Spanner?

### ISSUE THREAD

**Issue by mxlei01** [GoogleCloudPlatform/DataflowPythonSDK#63]
I notice that the Java version of Dataflow supports a lot more databases than Python according to this [link](https://beam.apache.org/documentation/io/built-in/).

Will there be more I/O connectors that the Python version supports in the future?

**Comment by chamikaramj** [comment]
There were discussions about adding a Python Spanner connector but I don't have a specific ETA yet.

In general we are trying to fill the connector gap between Java and Python. Features such as [cross-language transforms](https://beam.apache.org/roadmap/connectors-multi-sdk/) should help as well.

**Comment by mxlei01** [comment]
@chamikaramj 

Looking at this [link](https://docs.google.com/spreadsheets/d/1KDa_FGn1ShjomGd-UUDOhuh2q73de2tPz6BqHpzqvNI/edit#gid=0).

It looks like cross language transforms are currently work in progress.

By the way, if I write any Python/Java code right now, do I need port the code to Multi-SDK later?

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
